---
name: TF Tests

on:
  pull_request:
    paths: [.github/workflows/tf_tests.yaml, action.yml, tests/**]
    types: [opened, reopened, synchronize, closed]

jobs:
  tests:
    runs-on: ubuntu-24.04

    permissions:
      actions: read # Required to identify workflow run.
      checks: write # Required to add status summary.
      contents: read # Required to checkout repository.
      pull-requests: write # Required to add comment and label.

    strategy:
      fail-fast: false
      matrix:
        tool:
          - tofu
          - terraform
        test:
          - pass_one
          - pass_character_limit
          - fail_data_source_error
          - fail_format_diff
          - fail_invalid_resource_type

    steps:
      - name: Echo context
        env:
          GH_JSON: ${{ toJson(github) }}
        run: echo "$GH_JSON"

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup Tofu
        if: matrix.tool == 'tofu'
        uses: opentofu/setup-opentofu@12f4debbf681675350b6cd1f0ff8ecfbda62027b # v1.0.4
        with:
          tofu_version: v1.9.0
          tofu_wrapper: false

      - name: Setup Terraform
        if: matrix.tool == 'terraform'
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: v1.10.5
          terraform_wrapper: false

      - name: Provision TF
        id: tf
        continue-on-error: true
        uses: ./
        with:
          working-directory: tests/${{ matrix.test }}
          command: ${{ github.event.pull_request.merged && 'apply' || 'plan' }}
          arg-lock: ${{ github.event.pull_request.merged }}
          format: true
          validate: true
          tag-actor: never
          comment-pr: ${{ matrix.tool == 'tofu' && 'always' || 'never' }}
          tool: ${{ matrix.tool }}

      - name: Echo TF
        run: |
          echo "check-id: ${{ steps.tf.outputs.check-id }}"
          echo "command: ${{ steps.tf.outputs.command }}"
          echo "comment-id: ${{ steps.tf.outputs.comment-id }}"
          echo "diff: ${{ steps.tf.outputs.diff }}"
          echo "exitcode: ${{ steps.tf.outputs.exitcode }}"
          echo "identifier: ${{ steps.tf.outputs.identifier }}"
          echo "job-id: ${{ steps.tf.outputs.job-id }}"
          echo "plan-id: ${{ steps.tf.outputs.plan-id }}"
          echo "plan-url: ${{ steps.tf.outputs.plan-url }}"
          echo "result: ${{ steps.tf.outputs.result }}"
          echo "run-url: ${{ steps.tf.outputs.run-url }}"
          echo "summary: ${{ steps.tf.outputs.summary }}"
